[package]
name = "hidi2c-target-service"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
defmt = { workspace = true, optional = true }
log = { workspace = true, optional = true }

embassy-futures.workspace = true
embassy-time.workspace = true
embedded-hal.workspace = true
embedded-mcu-hal.workspace = true
embedded-services.workspace = true
generic-array.workspace = true
heapless.workspace = true           # TODO may not use this?
num_enum.workspace = true
odp-service-common.workspace = true
typenum.workspace = true
zerocopy.workspace = true

[features]
defmt = ["dep:defmt"]
log = ["dep:log", "embedded-services/log"]

[lints]
workspace = true
